DCGM Exporter Release 3.3.6-3.4.2
Signed-off-by: Rohit Arora <roarora@nvidia.com>

diff --git a/docker/Dockerfile.ubi9 b/docker/Dockerfile.ubi9
--- a/docker/Dockerfile.ubi9
+++ b/docker/Dockerfile.ubi9
@@ -1,4 +1,4 @@
-FROM nvcr.io/nvidia/cuda:12.3.2-base-ubi9 AS builder
+FROM nvcr.io/nvidia/cuda:12.4.1-base-ubi9 AS builder
 ARG GOLANG_VERSION
 WORKDIR /go/src/github.com/NVIDIA/dcgm-exporter
 RUN set -eux; \
@@ -8,28 +8,28 @@ RUN dnf clean all && rm -rf /usr/bin/go
 
 # Install Go official release
 RUN set -eux; \
-    url=; \
-    arch=$(uname -m) && if [ "${arch}" = "x86_64" ]; then arch=amd64; fi && if [ "${arch}" = "aarch64" ]; then arch=arm64; fi; \
+	url=; \
+	arch=$(uname -m) && if [ "${arch}" = "x86_64" ]; then arch=amd64; fi && if [ "${arch}" = "aarch64" ]; then arch=arm64; fi; \
 	case "$arch" in \
-		'amd64') \
-			url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"; \
-			;; \
-		'arm64') \
-			url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-arm64.tar.gz"; \
-			;; \
-		*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
+	'amd64') \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"; \
+	;; \
+	'arm64') \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-arm64.tar.gz"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
 	esac; \
 	build=; \
 	if [ -z "$url" ]; then \
-# https://github.com/golang/go/issues/38536#issuecomment-616897960
-		build=1; \
-		url="https://dl.google.com/go/go${GOLANG_VERSION}.src.tar.gz"; \
-		echo >&2; \
-		echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
-		echo >&2; \
+	# https://github.com/golang/go/issues/38536#issuecomment-616897960
+	build=1; \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.src.tar.gz"; \
+	echo >&2; \
+	echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
+	echo >&2; \
 	fi; \
-    wget -O go.tgz "$url" --progress=dot:giga; \
-    tar -C /usr/local -xzf go.tgz; \
+	wget -O go.tgz "$url" --progress=dot:giga; \
+	tar -C /usr/local -xzf go.tgz; \
 	rm go.tgz;
 ENV GOTOOLCHAIN=local
 ENV GOPATH /go
@@ -40,27 +40,12 @@ COPY . .
 
 RUN make binary check-format
 
-FROM nvcr.io/nvidia/cuda:12.3.2-base-ubi9
-LABEL io.k8s.display-name="NVIDIA DCGM Exporter"
-
+FROM nvcr.io/nvidia/cuda:12.4.1-base-ubi9
 ARG DCGM_VERSION
-
-RUN dnf update --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum \
-	&& dnf clean expire-cache && dnf install -y datacenter-gpu-manager-${DCGM_VERSION} libcap \
-	&& rm -rfd /usr/local/dcgm/bindings /usr/local/dcgm/sdk_samples /usr/share/nvidia-validation-suite
-
-COPY --from=builder /go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/dcgm-exporter /usr/bin/
-COPY etc /etc/dcgm-exporter
-
-ENV NVIDIA_VISIBLE_DEVICES=all
-# disable all constraints on the configurations required by NVIDIA container toolkit
-ENV NVIDIA_DISABLE_REQUIRE="true"
-# Required for DCP metrics
-ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,compat32
-
 ARG VERSION
+ARG DIST_DIR
 
-LABEL io.k8s.display-name="NVIDIA DCGM Eporter"
+LABEL io.k8s.display-name="NVIDIA DCGM Exporter"
 LABEL name="NVIDIA DCGM Exporter"
 LABEL vendor="NVIDIA"
 LABEL version="${VERSION}"
@@ -68,7 +53,19 @@ LABEL release="N/A"
 LABEL summary="Exports GPU Metrics to Prometheus"
 LABEL description="See summary"
 
+RUN dnf update --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum \
+	&& dnf clean expire-cache && dnf install -y datacenter-gpu-manager-${DCGM_VERSION} libcap \
+	&& rm -rfd /usr/local/dcgm/bindings /usr/local/dcgm/sdk_samples /usr/share/nvidia-validation-suite
+
 COPY ./LICENSE ./licenses/LICENSE
+COPY --from=builder /go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/dcgm-exporter /usr/bin/
+COPY ./etc /etc/dcgm-exporter
+
+ENV NVIDIA_VISIBLE_DEVICES=all
+# disable all constraints on the configurations required by NVIDIA container toolkit
+ENV NVIDIA_DISABLE_REQUIRE="true"
+# Required for DCP metrics
+ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,compat32
 
 ENV NO_SETCAP=
 COPY docker/dcgm-exporter-entrypoint.sh /usr/local/dcgm/dcgm-exporter-entrypoint.sh
diff --git a/docker/Dockerfile.ubuntu22.04 b/docker/Dockerfile.ubuntu22.04
--- a/docker/Dockerfile.ubuntu22.04
+++ b/docker/Dockerfile.ubuntu22.04
@@ -1,59 +1,70 @@
-FROM nvcr.io/nvidia/cuda:12.3.2-base-ubuntu22.04 AS builder
+FROM nvcr.io/nvidia/cuda:12.4.1-base-ubuntu22.04 AS builder
 ARG GOLANG_VERSION=1.21.5
 WORKDIR /go/src/github.com/NVIDIA/dcgm-exporter
 RUN set -eux; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
-		g++ \
-		gcc \
-		libc6-dev \
-		make \
-		pkg-config \
-        wget \
+	g++ \
+	gcc \
+	libc6-dev \
+	make \
+	pkg-config \
+	wget \
 	; \
 	rm -rf /var/lib/apt/lists/*
 RUN set -eux; \
 	arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
 	url=; \
 	case "$arch" in \
-		'amd64') \
-			url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"; \
-			;; \
-		'arm64') \
-			url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-arm64.tar.gz"; \
-			;; \
-		*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
+	'amd64') \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"; \
+	;; \
+	'arm64') \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.linux-arm64.tar.gz"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
 	esac; \
 	build=; \
 	if [ -z "$url" ]; then \
-# https://github.com/golang/go/issues/38536#issuecomment-616897960
-		build=1; \
-		url="https://dl.google.com/go/go${GOLANG_VERSION}.src.tar.gz"; \
-		echo >&2; \
-		echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
-		echo >&2; \
+	# https://github.com/golang/go/issues/38536#issuecomment-616897960
+	build=1; \
+	url="https://dl.google.com/go/go${GOLANG_VERSION}.src.tar.gz"; \
+	echo >&2; \
+	echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
+	echo >&2; \
 	fi; \
-    wget -O go.tgz "$url" --progress=dot:giga; \
-    tar -C /usr/local -xzf go.tgz; \
+	wget -O go.tgz "$url" --progress=dot:giga; \
+	tar -C /usr/local -xzf go.tgz; \
 	rm go.tgz;
 ENV GOTOOLCHAIN=local
 ENV GOPATH /go
 ENV PATH $GOPATH/bin:$PATH
 RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 1777 "$GOPATH"
-ENV PATH $PATH:/usr/local/go/bin   
+ENV PATH $PATH:/usr/local/go/bin
 COPY . .
 
 RUN make binary check-format
 
-FROM nvcr.io/nvidia/cuda:12.3.2-base-ubuntu22.04
-LABEL io.k8s.display-name="NVIDIA DCGM Exporter"
+FROM nvcr.io/nvidia/cuda:12.4.1-base-ubuntu22.04
 
+ARG VERSION
+ARG DCGM_VERSION
+ARG DIST_DIR
+
+LABEL io.k8s.display-name="NVIDIA DCGM Exporter"
+LABEL name="NVIDIA DCGM Exporter"
+LABEL vendor="NVIDIA"
+LABEL version="${VERSION}"
+LABEL release="N/A"
+LABEL summary="Exports GPU Metrics to Prometheus"
+LABEL description="See summary"
+
+COPY ./LICENSE ./licenses/LICENSE
 COPY --from=builder /go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/dcgm-exporter /usr/bin/
 COPY etc /etc/dcgm-exporter
 
-ARG DCGM_VERSION
 RUN apt-get update && apt-get install -y --no-install-recommends \
-    datacenter-gpu-manager=1:${DCGM_VERSION} libcap2-bin && apt-get purge --autoremove -y openssl \
+	datacenter-gpu-manager=1:${DCGM_VERSION} libcap2-bin && apt-get purge --autoremove -y openssl \
 	&& apt-get autoremove -y \
 	&& rm -rf /var/lib/apt/lists/* \
 	&& rm -rfd /usr/local/dcgm/bindings /usr/local/dcgm/sdk_samples /usr/share/nvidia-validation-suite
